// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Foundation;

namespace PresentScreenings.TableView
{
    public partial class MainWindowController : NSWindowController
	{
		#region Constants
        #endregion

        #region Properties
        public static AppDelegate App => (AppDelegate)NSApplication.SharedApplication.Delegate;
		public ActivatableToolbarItem PreviousDayToolbarItem => (ActivatableToolbarItem)_previousDayToolbarItem;
		public ActivatableToolbarItem NextDayToolbarItem => (ActivatableToolbarItem)_nextDayToolbarItem;
		public ActivatableToolbarItem WarningsToolbarItem => (ActivatableToolbarItem)_alerToolbarItem;
		public ActivatableToolbarItem TicketProblemsToolbarItem => _ticketAlertsToolbarItem;
		public NSToolbarItem ShowFilmInfoToolbarItem => _showFilmInfoToolbarItem;
		public NSToolbarItem VisitWebSiteToolbarItem => _vistWebsiteToolbarItem;
		public NSToolbarItem ShowScreeningInfoToolbarItem => _showScreeningInfoToolbarItem;
		public NSToolbarItem ShowRatingsToolbarItem => _showRatingsToolbarItem;
		public NSToolbarItem SaveToolbarItem => _saveToolbarItem;
		#endregion

		#region Constructors
		public MainWindowController (IntPtr handle) : base (handle)
		{
		}
        #endregion

        #region Override Methods
        public override void WindowDidLoad()
        {
            base.WindowDidLoad();

			// Tell the app delegate we're alive.
			App.MainWindowController = this;

			// Initialize the toolbar items.
			PreviousDayToolbarItem.Action = new ObjCRuntime.Selector("NavigateToPreviousDay:");
			PreviousDayToolbarItem.Active = App.Controller.Plan.NextDayExists(-1);
			PreviousDayToolbarItem.ToolTip = PreviousDayToolbarItem.Label;
			NextDayToolbarItem.Action = new ObjCRuntime.Selector("NavigateToNextDay:");
			NextDayToolbarItem.Active = App.Controller.Plan.NextDayExists(1);
			NextDayToolbarItem.ToolTip = NextDayToolbarItem.Label;
			ShowRatingsToolbarItem.ToolTip = ShowRatingsToolbarItem.Label;
			SaveToolbarItem.Action = new ObjCRuntime.Selector("SaveData:");
			SaveToolbarItem.ToolTip = SaveToolbarItem.Label;
			App.Controller.UpdateWarnings();
		}
		#endregion

		#region Custom Actions
		partial void ShowFilmInfo(Foundation.NSObject sender)
        {
			App.Controller.PerformSegue("ScreeningsToFilmInfo", sender);
        }

		partial void VisitWebSite(Foundation.NSObject sender)
        {
			ViewController.VisitFilmWebsite(App.Controller.CurrentFilm);
        }

		partial void ShowScreeningInfo(Foundation.NSObject sender)
        {
			App.Controller.ShowScreeningInfo();
        }

		[Action("NavigateToPreviousDay:")]
        private void NavigateToPreviousDay(NSObject sender)
		{
			App.Controller.SetNextDay(-1);
		}

		[Action("NavigateToNextDay:")]
        private void NavigateToNextDay(NSObject sender)
        {
			App.Controller.SetNextDay(1);
		}

		[Action("SaveData:")]
		private void SaveData(NSObject sender)
        {
			App.RunSaveDialog();
        }
		#endregion
	}
}
