// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Text;
using AppKit;
using CoreGraphics;
using Foundation;

namespace PresentScreenings.TableView
{
    /// <summary>
    /// Screening dialog controler, manages a dialog which displays extra information
    /// of a screening and in which editable screening properties can be changed.
    /// </summary>

    public partial class ScreeningDialogController : GoToScreeningDialog, IScreeningProvider
    {
        #region Constants
        private const float _xMargin = ControlsFactory.HorizontalMargin;
        private const float _yMargin = ControlsFactory.BigVerticalMargin;
        private const float _xBetweenLabels = ControlsFactory.HorizontalPixelsBetweenLabels;
        private const float _yBetweenViews = ControlsFactory.VerticalPixelsBetweenViews;
        private const float _yBetweenLabels = ControlsFactory.VerticalPixelsBetweenLabels;
        private const float _labelHeight = ControlsFactory.StandardLabelHeight;
        private const float _imageButtonWidth = ControlsFactory.StandardImageButtonWidth;
        private const float _buttonHeight = ControlsFactory.StandardButtonHeight;
        private const float _yBetweenControls = ControlsFactory.VerticalPixelsBetweenControls;
        private const float _subsectionLabelWidth = ControlsFactory.SubsectionLabelWidth;
        private const float _warningLabelHeight = _labelHeight + 2;
        private const float _warningLabelVerticalPositionCorrection = 6;
        private const float _warningImageSide = _warningLabelHeight;
        private const float _ratingBoxHeight = _labelHeight - 4;
        private const float _ratingBoxWidth = _labelHeight;

        #endregion

        #region Private Members
        private nfloat _contentWidth;
        private CGRect _warningImageRect;
        private CGRect _warningLabelFrame;
        private CGPoint _webSiteButtonOrigin;
        private CGRect _ratingFrame;
        private CGRect _attendanceFrame;
        private nfloat _fanControlsShift;
        private CGRect _scrollViewFrame;
        private Screening _screening;
        private DaySchemaScreeningControl _senderControl;
        private static ViewController _presentor;
        private List<Screening> _filmScreenings;
        private FilmScreeningControl _screeningInfoControl;
        private Dictionary<string, AttendanceCheckbox> _attendanceCheckboxByFilmFan;
        private NSTextField _warningLabel = null;
        private NSImageView _warningImageView = null;
        private NSView _sampleSubView;
        #endregion

        #region Properties
        public static ViewController Presentor
        {
            get => _presentor;
            set => _presentor = (ViewController)value;
        }

        public bool ScreeningInfoChanged
        {
            get => View.Window.DocumentEdited;
            private set
            {
                View.Window.DocumentEdited = value;
                if (value)
                {
                    ScreeningInfo.ScreeningInfoChanged = true;
                }
            }
        }
        #endregion

        #region Interface Implementation Properties
        public Screening CurrentScreening => Presentor.Plan.CurrScreening;
        public List<Screening> Screenings => Presentor.Plan.CurrScreening.FilmScreenings;
        public Film CurrentFilm => ViewController.GetFilmById(CurrentScreening.FilmId);
        #endregion

        #region Constructors
        public ScreeningDialogController(IntPtr handle) : base(handle)
        {
            _filmScreenings = new List<Screening> { };
            _attendanceCheckboxByFilmFan = new Dictionary<string, AttendanceCheckbox> { };
        }
        #endregion

        #region Override Methods
        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            // Tell the presentor we're alive.
            Presentor.ScreeningInfoDialog = this;
            Presentor.RunningPopupsCount += 1;

            // Initialize the list of screenings.
            _filmScreenings = _screening.FilmScreenings;

            // Set window delegate.
            View.Window.Delegate = new ScreeningRelatedWindowDelegate(View.Window, CloseDialog);

            // Set up the dialog layoput.
            SetUpLayout();

            // Populate the controls.
            SetControlValues();

            // Create the controls that are not defined in Xcode.
            CreateSubsectionLabel();
            CreateFilmFanControls();
            CreateScreeningsScrollView();
            CreateWarningLabel();
            CreateWarningImage();

            // Disable Resizing.
            DisableResizing(this, _sampleSubView);
        }

        public override void ViewWillDisappear()
        {
            // Tell the presentor we're gone.
            Presentor.RunningPopupsCount--;
            if (Presentor.RunningPopupsCount == 0)
            {
                Presentor.ScreeningInfoDialog = null;
            }
        }

        public override void PrepareForSegue(NSStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue(segue, sender);

            // Take action based on the segue name
            switch (segue.Identifier)
            {
                case "ScreeningToFilmInfo":
                    var filmInfoModal = segue.DestinationController as FilmInfoDialogController;
                    FilmInfoDialogController.Presentor = this;
                    filmInfoModal.BehaveAsPopover = true;
                    filmInfoModal.UseTitleBackground = true;
                break;
            }
        }

        public override void GoToScreening(Screening screening)
        {
            Presentor.GoToScreening(screening);
            CloseDialog();
        }
        #endregion

        #region Private Methods
        private void SetControlValues()
        {
            // Populate the Info Button.
            var imageByAvailability = new Dictionary<bool, NSImage> { };
            imageByAvailability[true] = _filmInfoButton.Image;
            imageByAvailability[false] = _filmInfoButton.AlternateImage;
            var isAvailable = ViewController.FilmInfoIsAvailable(_screening.Film);
            _filmInfoButton.Image = imageByAvailability[isAvailable];
            _filmInfoButton.Action = new ObjCRuntime.Selector("ShowFilmInfo:");
            _filmInfoButton.ToolTip = ControlsFactory.FilmInfoButtonToolTip(CurrentFilm);

            // Select the sending screening control in the screenings table.
            _senderControl.Selected = true;

            // Populate the labels.
            PopulateTitleLabel();
            _labelScreen.StringValue = _screening.Screen.ParseName;
            _labelTime.StringValue = _screening.ToLongTimeString();
            _labelPresent.StringValue = _screening.AttendeesString();

            // Populate the checkboxes.
            _checkboxTicketsBought.Activated += (s, e) => ToggleTicketsBought();
            _checkboxTicketsBought.State = ViewController.GetNSCellStateValue(_screening.TicketsBought);
            _checkboxSoldOut.Activated += (s, e) => ToggleSoldOut();
            _checkboxSoldOut.State = ViewController.GetNSCellStateValue(_screening.SoldOut);

            // Create the Visit Website button.
            CreateVisitFilmWebsiteButton();
        }

        private void PopulateTitleLabel()
        {
            _labelTitle.StringValue = $"{_screening.FilmTitle} ({_screening.Film.MinutesString})";
            if (_screening.Extra != string.Empty)
            {
                _labelTitle.StringValue += " (+ " + _screening.Extra + ")";
            }
            _labelTitle.LineBreakMode = NSLineBreakMode.TruncatingTail;
            _labelTitle.ToolTip = TitleLableTooltip();
        }

        private string TitleLableTooltip()
        {
            var film = _screening.Film;
            var builder = new StringBuilder(film.ToString());

            // If present, add the short description.
            if (film.FilmInfo.FilmDescription != string.Empty)
            {
                builder.AppendLine();
                builder.AppendLine();
                builder.Append(film.FilmInfo.FilmDescription);
            }

            // If present, add the screened films.
            builder.Append(film.FilmInfo.ScreenedFilmsTostring());

            return builder.ToString();
        }

        private void SetUpLayout()
        {
            _contentWidth = View.Frame.Width - 2 * _xMargin;

            // Set up frames for film fan controls.
            var xRating = _comboboxRating.Frame.X;
            var yRating = _comboboxRating.Frame.Y;
            _ratingFrame = new CGRect(xRating, yRating, _ratingBoxWidth, _ratingBoxHeight);

            _attendanceFrame = _checkboxIAttend.Frame;
            _attendanceFrame.Y = _checkboxIAttend.Frame.Y - _yBetweenLabels;

            // The original rating combo box and attendance checkbox can be
            // disposed now.
            _comboboxRating.RemoveFromSuperview();
            _comboboxRating.Dispose();
            _checkboxIAttend.RemoveFromSuperview();
            _checkboxIAttend.Dispose();

            // Set up a frame for the screenings scroll view.
            _fanControlsShift = _ratingFrame.Height + _yBetweenControls;
            var fanCount = ScreeningInfo.FilmFans.Count;
            var fanControlsHeight = fanCount * _fanControlsShift - _yBetweenControls;
            var yScrollerTop = _ratingFrame.Y - fanControlsHeight - _yBetweenControls;
            var scrollerHeight = yScrollerTop - _yBetweenViews - _buttonHeight - _yMargin;
            var yScroller = yScrollerTop - scrollerHeight;
            _scrollViewFrame = new CGRect(_xMargin, yScroller, _contentWidth, scrollerHeight);

            // Set up warning image frame.
            var yImage = _closeButton.Frame.Y + _warningLabelVerticalPositionCorrection;
            _warningImageRect = new CGRect(_xMargin, yImage, _warningImageSide, _warningImageSide);

            // Set up warning label frame.
            var yLabel = yImage;
            var width = _contentWidth - _closeButton.Frame.Width - _imageButtonWidth - _warningImageSide - _xBetweenLabels;
            var xLabel = _xMargin + _warningImageSide + _xBetweenLabels;
            _warningLabelFrame = new CGRect(xLabel, yLabel, width, _warningLabelHeight);

            // Set up origin for button to visit film site.
            var xWeb = _closeButton.Frame.X - _imageButtonWidth;
            var yWeb = _closeButton.Frame.Y;
            _webSiteButtonOrigin = new CGPoint(xWeb, yWeb);
        }

        private void CreateSubsectionLabel()
        {
            var frame = _labelTitle.Frame;
            var leftPosition = frame.X + frame.Width + _xBetweenLabels;
            var subsectionRect = new CGRect(leftPosition, frame.Y, _subsectionLabelWidth, frame.Height);
            var subsectionLabel = ControlsFactory.NewSubsectionLabel(subsectionRect, _screening.Film, true);
            View.AddSubview(subsectionLabel);
        }

        private void CreateFilmFanControls()
        {
            // Set the font for the Attendance checkboxes.
            var checkBoxFont = _checkboxTicketsBought.Font;

            // Create the fan controls.
            foreach (var filmfan in ScreeningInfo.FilmFans)
            {
                // Create the Rating box for this film fan.
                var fanRatingLabel = ControlsFactory.NewStandardLabel(_ratingFrame, true);
                fanRatingLabel.Alignment = NSTextAlignment.Right;
                fanRatingLabel.StringValue = ViewController.GetFilmFanFilmRating(_screening.FilmId, filmfan).ToString();
                View.AddSubview(fanRatingLabel);

                // Create the Attendance checkbox for this film fan.
                var fanCheckbox = new AttendanceCheckbox(_attendanceFrame)
                {
                    Title = filmfan,
                    Font = checkBoxFont,
                    State = AttendanceCheckbox.GetAttendanceState(_screening.FilmFanAttends(filmfan))
                };
                fanCheckbox.Activated += (s, e) => ToggleAttendance(filmfan);
                View.AddSubview(fanCheckbox);

                // Link the checkbox to the film fan.
                _attendanceCheckboxByFilmFan.Add(filmfan, fanCheckbox);

                // Shift the frames.
                _ratingFrame.Y -= _fanControlsShift;
                _attendanceFrame.Y -= _fanControlsShift;
            }
        }

        private void CreateScreeningsScrollView()
        {
            // Get the screenings of the selected film.
            var screenings = _filmScreenings;

            // Create the screenings view.
            var xScreenings = screenings.Count * (_labelHeight + _yBetweenLabels);
            var screeningsViewFrame = new CGRect(0, 0, _contentWidth, xScreenings);
            var screeningsView = new NSView(screeningsViewFrame);

            // Create the scroll view.
            var scrollView = ControlsFactory.NewStandardScrollView(_scrollViewFrame, screeningsView, true);
            View.AddSubview(scrollView);

            // Display the screenings.
            DisplayScreeningControls(screenings, _screening.FilmId, screeningsView, GoToScreening, ref _screeningInfoControl);

            // Scroll to the selected screening.
            ScrollScreeningToVisible(CurrentScreening, scrollView);

            // Set sample view used to disable resizing.
            _sampleSubView = scrollView;
        }

        private void CreateVisitFilmWebsiteButton()
        {
            var websiteButton = ControlsFactory.NewVisitWebsiteButton(_webSiteButtonOrigin, CurrentFilm);
            websiteButton.Enabled = true;
            View.AddSubview(websiteButton);
        }

        private void CreateWarningLabel()
        {
            _warningLabel = ControlsFactory.NewScreeningWarningLabel(_warningLabelFrame, _screening);
            View.AddSubview(_warningLabel);
        }

        private void CreateWarningImage()
        {
            _warningImageView = ControlsFactory.NewWarningImageView(_warningImageRect);
            ControlsFactory.UpdateWarningImage(View, _warningImageView, _screening);
        }
        #endregion

        #region Public Methods
        public void CloseDialog()
        {
            if (ScreeningInfoChanged)
            {
                // Save the screening info.
                SaveScreeningInfo();

                // Unset the Document Edited flag of the presentor.
                Presentor.ScreeningInfoChanged = false;
            }

            // Close the dialog.
            Presentor.DismissViewController(this);
        }

        public static void SaveScreeningInfo()
        {
            // Save the screening info.
            ViewController.App.WriteScreeningInfo();
            ScreeningInfo.ScreeningInfoChanged = false;

            // Trigger a local notification.
            string title = "Screening Info Saved";
            string text = $"Screening info has been saved in {AppDelegate.DocumentsFolder}.";
            AlertRaiser.RaiseNotification(title, text);
        }

        public void PopulateDialog(DaySchemaScreeningControl sender)
        {
            _senderControl = sender;
            _screening = sender.Screening;
        }

        public void ToggleTicketsBought()
        {
            _screening.TicketsBought = !_screening.TicketsBought;
            UpdateScreeningInfo();
        }

        public void ToggleSoldOut()
        {
            _screening.SoldOut = !_screening.SoldOut;
            UpdateScreeningInfo();
        }

        public void ToggleAttendance(string filmFan)
        {
            _screening.ToggleFilmFanAttendance(filmFan);
            UpdateScreeningInfo();
            var attendanceState = AttendanceCheckbox.GetAttendanceState(_screening.FilmFanAttends(filmFan));
            _attendanceCheckboxByFilmFan[filmFan].State = attendanceState;
        }

        public void UpdateWarning()
        {
            Presentor.UpdateWarning(_screening);
            ControlsFactory.UpdateScreeningWarningLabel(_warningLabel, _screening);
            ControlsFactory.UpdateWarningImage(View, _warningImageView, _screening);
        }

        public void UpdateScreeningInfo()
        {
            _labelPresent.StringValue = _screening.AttendeesString();
            Presentor.UpdateAttendanceStatus(_screening, false);
            Presentor.ReloadScreeningsView();
            UpdateWarning();
            UpdateScreeningControls();
            _screeningInfoControl.ReDraw();
            _closeButton.Title = ControlsFactory.TitleByChanged[true];
            ScreeningInfoChanged = true;
        }

        public void UpdateMovedScreeningInfo()
        {
            _labelTime.StringValue = _screening.ToLongTimeString();
            UpdateScreeningInfo();
        }
        #endregion

        #region Custom Actions
        partial void AcceptDialog(Foundation.NSObject sender)
        {
            RaiseDialogAccepted();
            CloseDialog();
        }

        partial void CancelDialog(Foundation.NSObject sender)
        {
            RaiseDialogCanceled();
            CloseDialog();
        }

        partial void ToggleTicketsBought(NSObject sender)
        {
            ToggleTicketsBought();
            _checkboxTicketsBought.State = ViewController.GetNSCellStateValue(_screening.TicketsBought);
        }

        partial void ToggleSoldOut(NSObject sender)
        {
            ToggleSoldOut();
            _checkboxSoldOut.State = ViewController.GetNSCellStateValue(_screening.SoldOut);
        }

        [Action("ToggleAttendance:")]
        internal void ToggleAttendance(NSObject sender)
        {
            string filmFan = ((NSMenuItem)sender).Title;
            ToggleAttendance(filmFan);
        }

        [Action("NavigateFilmScreening:")]
        internal void NavigateFilmScreening(NSObject sender)
        {
            var screening = ScreeningMenuDelegate.FilmScreening(((NSMenuItem)sender).Title);
            GoToScreening(screening);
        }

        [Action("ShowFilmInfo:")]
        internal void ShowFilmInfo(NSObject sender)
        {
            PerformSegue("ScreeningToFilmInfo", sender);
        }
        #endregion

        #region Events
        public EventHandler DialogAccepted;

        internal void RaiseDialogAccepted()
        {
            DialogAccepted?.Invoke(this, EventArgs.Empty);
        }

        public EventHandler DialogCanceled;

        internal void RaiseDialogCanceled()
        {
            DialogCanceled?.Invoke(this, EventArgs.Empty);
        }
        #endregion
    }
}
