# Generated by Django 3.2.9 on 2023-05-30 17:53

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=72)),
            ],
            options={
                'db_table': 'city',
                'unique_together': {('name', 'country')},
            },
            managers=[
                ('cities', django.db.models.manager.Manager()),
            ],
        ),
    ]
