# Generated by Django 3.2.9 on 2023-05-30 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.IntegerField(unique=True)),
                ('parse_name', models.CharField(max_length=64)),
                ('abbreviation', models.CharField(max_length=8, null=True)),
                ('address_type', models.IntegerField(choices=[(3, 'Location'), (2, 'Ondemand'), (1, 'Online')])),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theater')),
            ],
            options={
                'db_table': 'screen',
            },
            managers=[
                ('screens', django.db.models.manager.Manager()),
            ],
        ),
    ]
