# Generated by Django 3.2.9 on 2024-01-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='address_type',
            field=models.IntegerField(choices=[(3, 'Physical'), (2, 'Ondemand'), (1, 'Online')]),
        ),
    ]
