# Generated by Django 4.2.8 on 2025-09-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0004_alter_screen_address_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='theater',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_name_country'),
        ),
        migrations.AddConstraint(
            model_name='theater',
            constraint=models.UniqueConstraint(fields=('city', 'abbreviation'), name='unique_city_abbreviation'),
        ),
    ]
