# Generated by Django 4.2.8 on 2026-06-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0005_alter_city_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(fields=('theater', 'id'), name='unique_theater_screen_id'),
        ),
    ]
