# Generated by Django 4.2.8 on 2026-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0006_screen_unique_theater_screen_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(fields=('theater', 'parse_name'), name='unique_theater_screen_parse_name'),
        ),
    ]
