# Generated by Django 4.2.8 on 2026-06-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0007_screen_unique_theater_screen_parse_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(fields=('theater', 'abbreviation'), name='unique_theater_abbreviation'),
        ),
    ]
