# Generated by Django 3.2.9 on 2022-12-16 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivals', '0014_remove_festival_border_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=8)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
            options={
                'db_table': 'sections',
                'unique_together': {('festival', 'section_id')},
            },
            managers=[
                ('sections', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=4048)),
                ('url', models.URLField(null=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section')),
            ],
            options={
                'db_table': 'subsections',
                'unique_together': {('festival', 'subsection_id')},
            },
            managers=[
                ('subsections', django.db.models.manager.Manager()),
            ],
        ),
    ]
