# Generated by Django 3.2.9 on 2023-05-30 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theaters', '0003_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('home_city', models.ForeignKey(db_column='pity_id', on_delete=django.db.models.deletion.CASCADE, to='theaters.city')),
            ],
            options={
                'db_table': 'film_festival_base',
            },
            managers=[
                ('festival_bases', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('edition', models.CharField(blank=True, max_length=16, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('festival_color', models.CharField(choices=[('tomato', 'tomato'), ('red', 'red'), ('orange', 'orange'), ('maroon', 'maroon'), ('yellow', 'yellow'), ('lime', 'lime'), ('green', 'green'), ('olive', 'olive'), ('turquoise', 'turquoise'), ('blue', 'blue'), ('navy', 'navy'), ('fuchsia', 'fuchsia'), ('purple', 'purple'), ('silver', 'silver'), ('grey', 'grey'), ('black', 'black')], default='green', max_length=24)),
                ('base', models.ForeignKey(db_column='mnemonic', on_delete=django.db.models.deletion.CASCADE, to='festivals.festivalbase')),
            ],
            options={
                'db_table': 'film_festival',
                'unique_together': {('base', 'year', 'edition')},
            },
            managers=[
                ('festivals', django.db.models.manager.Manager()),
            ],
        ),
    ]
