# Generated by Django 3.2.9 on 2023-06-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_screen'),
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalbase',
            name='home_city',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='theaters.city'),
        ),
    ]
