# Generated by Django 4.2.8 on 2026-06-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_alter_festivalbase_home_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='festival',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='festival',
            constraint=models.UniqueConstraint(fields=('base', 'year', 'edition'), name='unique_base_year_edition'),
        ),
    ]
