# Generated by Django 3.2.9 on 2022-05-29 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0004_alter_film_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5580)),
            preserve_default=False,
        ),
    ]
