# Generated by Django 3.2.9 on 2022-05-31 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0008_auto_20220530_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(0, 'Unrated'), (1, 'Very Bad'), (2, 'Bad'), (3, 'Very Insufficient'), (4, 'Insufficient'), (5, 'Almost Sufficient'), (6, 'Sufficient'), (7, 'Very Sufficient'), (8, 'Good'), (9, 'Very Good'), (10, 'Excellent')])),
            ],
        ),
        migrations.AlterModelManagers(
            name='film',
            managers=[
                ('films', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FilmFanFilmRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_list.filmfan')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_list.film')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_list.filmrating')),
            ],
        ),
    ]
