# Generated by Django 3.2.9 on 2022-05-31 17:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0009_auto_20220531_1904'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='filmfan',
            managers=[
                ('film_fans', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='filmfanfilmrating',
            managers=[
                ('fan_ratings', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='filmrating',
            managers=[
                ('film_ratings', django.db.models.manager.Manager()),
            ],
        ),
    ]
