# Generated by Django 3.2.9 on 2022-05-31 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0011_auto_20220531_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmfanfilmrating',
            old_name='film_id',
            new_name='film',
        ),
    ]
