# Generated by Django 3.2.9 on 2022-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0014_auto_20220601_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmfanfilmrating',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Very Bad'), (2, 'Bad'), (3, 'Very Insufficient'), (4, 'Insufficient'), (5, 'Below Mediocre'), (6, 'Mediocre'), (7, 'Indecisive'), (8, 'Good'), (9, 'Very Good'), (10, 'Excellent')]),
        ),
        migrations.AlterModelTable(
            name='filmfanfilmrating',
            table='film_fan_film_rating',
        ),
    ]
