# Generated by Django 3.2.9 on 2022-06-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0017_tablecolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableColor',
        ),
    ]
