# Generated by Django 3.2.9 on 2022-06-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0018_delete_tablecolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmfan',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filmfanfilmrating',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Already Seen'), (2, 'Will See'), (3, 'Very Bad'), (4, 'Bad'), (5, 'Below Mediocre'), (6, 'Mediocre'), (7, 'Indecisive'), (8, 'Good'), (9, 'Very Good'), (10, 'Excellent')]),
        ),
    ]
