# Generated by Django 3.2.9 on 2022-06-14 15:50

from django.db import migrations
from FilmRatings import tools


def reload_film_ratings(apps, schema_editor):
    # Get the model from the versioned app registry to be sure to get
    # the right version.
    fan_rating_class = apps.get_model("film_list", "FilmFanFilmRating")

    # Get a reference to the database.
    db_alias = schema_editor.connection.alias

    # Delete all existing fan ratings.
    fan_rating_class.fan_ratings.using(db_alias).delete()

    # Get a list of fresh fan ratings.
    fan_ratings = tools.Festival('MTMF', 2022).read_ratings()

    # Add the new fan ratings to the database.
    fan_rating_class.fan_ratings.using(db_alias).bulk_create(fan_ratings)


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0022_load_fans'),
    ]

    # Operation commented out in order to get a working test database.
    operations = [
        # migrations.RunPython(reload_film_ratings)
    ]
