# Generated by Django 3.2.9 on 2022-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0023_reload_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmfan',
            name='represented_by_user',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
