# Generated by Django 3.2.9 on 2022-07-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0024_filmfan_represented_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmfan',
            name='is_logged_in',
        ),
        migrations.RemoveField(
            model_name='filmfan',
            name='represented_by_user',
        ),
    ]
