# Generated by Django 3.2.9 on 2022-12-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0029_auto_20220806_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='section',
            new_name='subsection',
        ),
    ]
