# Generated by Django 3.2.9 on 2023-06-04 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivals', '0002_alter_festivalbase_home_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=8)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
            ],
            options={
                'db_table': 'section',
                'unique_together': {('festival', 'section_id')},
            },
            managers=[
                ('sections', django.db.models.manager.Manager()),
            ],
        ),
    ]
