# Generated by Django 3.2.9 on 2023-06-04 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_alter_festivalbase_home_city'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsection_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=4048)),
                ('url', models.URLField(null=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.festival')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section')),
            ],
            options={
                'db_table': 'subsection',
                'unique_together': {('festival', 'subsection_id')},
            },
            managers=[
                ('subsections', django.db.models.manager.Manager()),
            ],
        ),
    ]
