# Generated by Django 4.2.8 on 2024-07-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_subsection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together=set(),
        ),
    ]
