# Generated by Django 4.2.8 on 2024-07-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_alter_festivalbase_home_city'),
        ('sections', '0003_alter_section_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('festival', 'section_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together={('festival', 'subsection_id')},
        ),
    ]
