# Generated by Django 4.2.8 on 2024-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_alter_section_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subsection',
            constraint=models.UniqueConstraint(fields=('subsection_id', 'section'), name='unique_subsection_id_section'),
        ),
    ]
