# Generated by Django 4.2.8 on 2024-07-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_alter_subsection_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='festival',
        ),
    ]
