# Generated by Django 4.2.8 on 2026-06-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_remove_subsection_festival'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('festival', 'section_id'), name='unique_festival_section_id'),
        ),
    ]
