# Generated by Django 4.2.8 on 2026-07-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_section_unique_festival_section_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
    ]
