# Generated by Django 3.2.9 on 2022-06-06 19:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('border_color', models.CharField(choices=[('red', 'red'), ('maroon', 'maroon'), ('green', 'green'), ('lime', 'lime'), ('blue', 'blue'), ('navy', 'navy'), ('black', 'black')], default='lime', max_length=10)),
            ],
            options={
                'db_table': 'table_color',
            },
            managers=[
                ('table_colors', django.db.models.manager.Manager()),
            ],
        ),
    ]
