# Generated by Django 3.2.9 on 2022-06-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolor',
            name='picked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablecolor',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
