# Generated by Django 3.2.9 on 2023-06-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20230605_2143'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='FilmFan',
        # ),
    ]
