# Generated by Django 3.2.9 on 2022-05-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_nr', models.IntegerField()),
                ('film_id', models.IntegerField()),
                ('sort_title', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('title_language', models.CharField(max_length=2)),
                ('section', models.CharField(max_length=32)),
                ('medium_category', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'films',
            },
        ),
    ]
