# Generated by Django 3.2.9 on 2022-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmList', '0002_auto_20220529_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='section',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
