# Generated by Django 3.2.9 on 2022-05-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmList', '0005_film_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('seq_nr', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'film_fans',
            },
        ),
    ]
