# Generated by Django 3.2.9 on 2022-05-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmList', '0010_auto_20220531_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmfanfilmrating',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Very Bad'), (2, 'Bad'), (3, 'Very Insufficient'), (4, 'Insufficient'), (5, 'Almost Sufficient'), (6, 'Sufficient'), (7, 'Amply Sufficient'), (8, 'Good'), (9, 'Very Good'), (10, 'Excellent')]),
        ),
        migrations.DeleteModel(
            name='FilmRating',
        ),
    ]
