# Generated by Django 3.2.9 on 2022-06-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmList', '0019_auto_20220614_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmfan',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmfan',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
