# Generated by Django 3.2.9 on 2022-06-14 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmList', '0020_auto_20220614_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmfanfilmrating',
            name='film_fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmList.filmfan'),
        ),
    ]
