# Generated by Django 3.2.9 on 2023-06-04 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmFanFilmRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, 'Unrated'), (1, 'Already Seen'), (2, 'Will See'), (3, 'Very Bad'), (4, 'Bad'), (5, 'Below Mediocre'), (6, 'Mediocre'), (7, 'Indecisive'), (8, 'Good'), (9, 'Very Good'), (10, 'Excellent')])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('film_fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.filmfan')),
            ],
            options={
                'db_table': 'film_rating',
                'unique_together': {('film', 'film_fan')},
            },
            managers=[
                ('film_ratings', django.db.models.manager.Manager()),
            ],
        ),
    ]
