# Generated by Django 3.2.9 on 2023-06-05 19:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_filmfanfilmrating'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='FilmFan',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=16, unique=True)),
        #         ('seq_nr', models.IntegerField(unique=True)),
        #         ('is_admin', models.BooleanField(default=False)),
        #     ],
        #     options={
        #         'db_table': 'film_fan',
        #     },
        #     managers=[
        #         ('film_fans', django.db.models.manager.Manager()),
        #     ],
        # ),
        # migrations.AlterField(
        #     model_name='filmfanfilmrating',
        #     name='film_fan',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.filmfan'),
        # ),
    ]
