# Generated by Django 3.2.9 on 2024-02-19 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('films', '0002_filmfanfilmrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmFanFilmVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('film_fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.filmfan')),
            ],
            options={
                'db_table': 'film_vote',
                'unique_together': {('film', 'film_fan')},
            },
            managers=[
                ('film_votes', django.db.models.manager.Manager()),
            ],
        ),
    ]
