# Generated by Django 3.2.9 on 2024-03-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_filmfanfilmvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmfanfilmvote',
            name='vote',
            field=models.IntegerField(),
        ),
    ]
