# Generated by Django 3.2.9 on 2024-03-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_filmfanfilmvote_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmfanfilmvote',
            name='vote',
            field=models.IntegerField(choices=[(0, 'Unrated'), (3, 'Very Bad'), (4, 'Bad'), (5, 'Below Mediocre'), (6, 'Mediocre'), (7, 'Indecisive'), (8, 'Good'), (9, 'Very Good'), (10, 'Excellent')]),
        ),
    ]
