# Generated by Django 4.0.10 on 2024-06-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_filmfanfilmvote_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='reviewer',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
