# Generated by Django 4.2.8 on 2024-07-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_alter_section_unique_together_and_more'),
        ('films', '0006_film_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.subsection'),
        ),
    ]
