# Generated by Django 4.2.8 on 2025-09-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_film_subsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='main_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.film'),
        ),
    ]
