# Generated by Django 4.2.8 on 2025-12-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_film_main_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmfanfilmrating',
            name='original_rating',
            field=models.IntegerField(choices=[(0, 'Unrated'), (1, 'Already Seen'), (2, 'Will See'), (3, 'Very Bad'), (4, 'Bad'), (5, 'Below Mediocre'), (6, 'Mediocre'), (7, 'Indecisive'), (8, 'Good'), (9, 'Very Good'), (10, 'Excellent')], default=0),
            preserve_default=False,
        ),
    ]
