# Generated by Django 4.2.8 on 2026-06-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_filmfanfilmrating_original_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='film',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='film',
            constraint=models.UniqueConstraint(fields=('festival', 'film_id'), name='unique_festival_film_id'),
        ),
    ]
