# Generated by Django 4.2.8 on 2026-06-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_film_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmfanfilmrating',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='filmfanfilmrating',
            constraint=models.UniqueConstraint(fields=('film', 'film_fan'), name='unique_film_fan'),
        ),
    ]
