# Generated by Django 4.2.8 on 2026-06-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_alter_filmfanfilmrating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmfanfilmvote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='filmfanfilmvote',
            constraint=models.UniqueConstraint(fields=('film', 'film_fan'), name='unique_film_fan_vote'),
        ),
    ]
