# Generated by Django 3.2.9 on 2023-05-21 15:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'cities',
                'unique_together': {('name', 'country')},
            },
            managers=[
                ('cities', django.db.models.manager.Manager()),
            ],
        ),
    ]
