# Generated by Django 3.2.9 on 2023-05-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parse_name', models.CharField(max_length=64)),
                ('abbreviation', models.CharField(max_length=10)),
                ('priority', models.IntegerField(choices=[(0, 'No Go'), (1, 'Low'), (2, 'High')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.city')),
            ],
            options={
                'db_table': 'theaters',
                'unique_together': {('city_id', 'abbreviation')},
            },
        ),
    ]
