# Generated by Django 3.2.9 on 2023-05-28 17:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_screen'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='screen',
            managers=[
                ('screens', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='theater',
            managers=[
                ('theaters', django.db.models.manager.Manager()),
            ],
        ),
    ]
