# Generated by Django 3.2.9 on 2023-05-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0004_auto_20230528_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screen',
        ),
    ]
