# Generated by Django 3.2.9 on 2023-05-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0005_delete_screen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
