# Generated by Django 3.2.9 on 2023-05-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0006_delete_theater'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
