# Generated by Django 3.2.9 on 2023-05-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0009_theater'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
