Constants:
    MaxShortMinutes: 40
    LowestPlannableRating: 8
    WalkMinutesSameTheater: 15
    TravelMinutesOtherTheater: 40

Paths:
    FestivalRootDirectory: Documents/Film
    CommonDataDirectory: Documents/Film/CommonFestivalData
    LoaderSharedDirectory: Projects/FilmFestivalPlanner/FilmFestivalLoader/Shared

Headers:
    FilmsFileHeader:
        - seq-nr
        - film-id
        - sort
        - title
        - title-language
        - section
        - duration
        - medium-category
        - reviewer
        - url
