// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace PresentScreenings.TableView
{
	public partial class AvailabilityDialogControler : NSViewController
	{
		public AvailabilityDialogControler (IntPtr handle) : base (handle)
		{
		}
	}
}
