# Generated by Django 4.2.8 on 2024-08-13 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theaters', '0004_alter_screen_address_type'),
        ('films', '0007_alter_film_subsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('subtitles', models.CharField(max_length=24)),
                ('q_and_a', models.BooleanField()),
                ('combination_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combined_screening', to='films.film')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.screen')),
            ],
            options={
                'db_table': 'screening',
            },
            managers=[
                ('screenings', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='screening',
            constraint=models.UniqueConstraint(fields=('film', 'screen', 'start_dt'), name='unique_film_screen_start'),
        ),
    ]
