# Generated by Django 4.2.8 on 2024-08-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0002_attendance_attendance_unique_fan_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='status',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Unavailable'), (2, 'Attends'), (3, 'Friend Attends'), (4, 'Attends Film'), (5, 'Time Overlap'), (6, 'No Travel Time'), (7, 'Needs Tickets')], default=0),
        ),
    ]
