# Generated by Django 4.2.8 on 2024-09-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0003_screening_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='status',
        ),
    ]
