# Generated by Django 4.2.8 on 2024-12-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0004_remove_screening_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='auto_planned',
            field=models.BooleanField(default=False),
        ),
    ]
