# Generated by Django 4.2.8 on 2025-08-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0007_remove_attendance_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='subtitles',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
