# Generated by Django 4.2.8 on 2026-03-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0008_alter_screening_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
