# Generated by Django 3.2.9 on 2022-06-12 14:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('edition', models.CharField(max_length=16, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('border_color', models.CharField(choices=[('red', 'red'), ('maroon', 'maroon'), ('green', 'green'), ('lime', 'lime'), ('blue', 'blue'), ('navy', 'navy'), ('black', 'black')], default='lime', max_length=10)),
            ],
            options={
                'db_table': 'film_festival',
                'unique_together': {('mnemonic', 'year', 'edition')},
            },
            managers=[
                ('festivals', django.db.models.manager.Manager()),
            ],
        ),
    ]
