# Generated by Django 3.2.9 on 2022-06-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='edition',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
