# Generated by Django 3.2.9 on 2022-06-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_alter_festival_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='is_current_festival',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='festival',
            name='border_color',
            field=models.CharField(choices=[('tomato', 'tomato'), ('red', 'red'), ('orange', 'orange'), ('maroon', 'maroon'), ('yellow', 'yellow'), ('lime', 'lime'), ('green', 'green'), ('olive', 'olive'), ('turquoise', 'turquoise'), ('blue', 'blue'), ('navy', 'navy'), ('fuchsia', 'fuchsia'), ('purple', 'purple'), ('silver', 'silver'), ('grey', 'grey'), ('black', 'black')], default='green', max_length=10),
        ),
    ]
