# Generated by Django 3.2.9 on 2022-06-13 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0006_alter_festivalbase_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='name',
        ),
        migrations.AlterField(
            model_name='festival',
            name='mnemonic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.festivalbase'),
        ),
    ]
