# Generated by Django 3.2.9 on 2022-06-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0007_auto_20220613_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='mnemonic',
            field=models.ForeignKey(db_column='mnemonic', on_delete=django.db.models.deletion.CASCADE, to='festivals.festivalbase'),
        ),
    ]
