# Generated by Django 3.2.9 on 2022-06-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0008_alter_festival_mnemonic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festival',
            old_name='mnemonic',
            new_name='base',
        ),
        migrations.AlterUniqueTogether(
            name='festival',
            unique_together={('base', 'year', 'edition')},
        ),
    ]
