# Generated by Django 3.2.9 on 2022-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0009_auto_20220614_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalbase',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
