# Generated by Django 3.2.9 on 2022-07-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0011_auto_20220624_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='is_current_festival',
        ),
    ]
