# Generated by Django 3.2.9 on 2023-05-29 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0011_theater'),
        ('festivals', '0014_remove_festival_border_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityProxy',
            fields=[
                ('city_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='theaters.city')),
            ],
            bases=('theaters.city',),
            managers=[
                ('cities', django.db.models.manager.Manager()),
            ],
        ),
    ]
