# Generated by Django 3.2.9 on 2023-05-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0011_theater'),
        ('festivals', '0016_dummycity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityProxy',
        ),
    ]
