# Generated by Django 3.2.9 on 2023-05-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0018_dummybase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyBase',
        ),
    ]
