# Generated by Django 3.2.9 on 2023-05-29 18:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0019_delete_dummybase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'dummy_base',
            },
            managers=[
                ('dummy_bases', django.db.models.manager.Manager()),
            ],
        ),
    ]
