# Generated by Django 3.2.9 on 2023-05-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0020_dummybase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummybase',
            name='home_city',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='festivals.dummycity'),
            preserve_default=False,
        ),
    ]
