# Generated by Django 3.2.9 on 2023-05-29 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0011_theater'),
        ('festivals', '0021_dummybase_home_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummybase',
            name='smart_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theaters.city'),
            preserve_default=False,
        ),
    ]
