# Generated by Django 3.2.9 on 2023-06-12 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0022_dummybase_smart_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyBase',
        ),
    ]
