# Generated by Django 3.2.9 on 2023-06-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0023_delete_dummybase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyCity',
        ),
    ]
