# Generated by Django 4.2.8 on 2024-09-20 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.filmfan')),
            ],
            options={
                'db_table': 'availability',
            },
            managers=[
                ('availabilities', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='availabilities',
            constraint=models.UniqueConstraint(fields=('fan', 'start_dt'), name='unique_fan_start'),
        ),
    ]
